BaoCaoCuoiKy/www/WebFinalProject/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebFinalProject.Models;

namespace WebFinalProject.Controllers
{
    public class PostController : Controller
    {
        private WebProjectContext db = new WebProjectContext();

        //
        // GET: /Post/

        public ActionResult Index()
        {
            var post = db.Post.Include(p => p.ChiTietTheLoaiTruyen);
            return View(post.ToList());
        }
        public ActionResult AnhDuongLaCuaToi(int id=1)
        
        {
            Post post = db.Post.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }
        public ActionResult SearchTags(int id = 0)
        {
            Tag tag = db.Tag.Find(id);
            return View(tag);
        }
        //
        // GET: /Post/Details/5

        public ActionResult Details(int id = 1)
        {

            Post post = db.Post.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }
         public ActionResult ResultAfterCreatePost()
        {
            return View();
        }
        //
        // GET: /Post/Create

        public ActionResult Create()
        {
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            ViewBag.ChiTietTheLoaiTruyenID = new SelectList(db.ChiTietTheLoaiTruyen, "ChiTietTheLoaiTruyenID", "TenChiTietTheLoaiTruyen");
            return View();
        }

        //
        // POST: /Post/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Post post, string NoiDung)
        {
            if (ModelState.IsValid)
            {
                post.NgayDang = DateTime.Now;
                post.UserId = db.UserProfiles.Where(p => p.UserName == User.Identity.Name).Select(a => a.UserId).Single();
                List<Tag> Tags = new List<Tag>();
                string[] TagContent = NoiDung.Split(',');
                foreach (string item in TagContent)
                {
                    Tag tagExits = null;
                    var ListTag = db.Tag.Where(y => y.NoiDung.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        tagExits = ListTag.First();
                        tagExits.Posts.Add(post);
                    }
                    else
                    {
                        tagExits = new Tag();
                        tagExits.NoiDung = item;
                        tagExits.Posts = new List<Post>();
                        tagExits.Posts.Add(post);
                    }
                    Tags.Add(tagExits);
                }
                post.Tags = Tags;

                db.Post.Add(post);
                db.SaveChanges();
                return RedirectToAction("ResultAfterCreatePost");
            }

            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserId);
            ViewBag.ChiTietTheLoaiTruyenID = new SelectList(db.ChiTietTheLoaiTruyen, "ChiTietTheLoaiTruyenID", "TenChiTietTheLoaiTruyen", post.ChiTietTheLoaiTruyenID);
            return View(post);
        }

        //
        // GET: /Post/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Post post = db.Post.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserId);
            ViewBag.ChiTietTheLoaiTruyenID = new SelectList(db.ChiTietTheLoaiTruyen, "ChiTietTheLoaiTruyenID", "TenChiTietTheLoaiTruyen", post.ChiTietTheLoaiTruyenID);
            return View(post);
        }

        //
        // POST: /Post/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserId);
            ViewBag.ChiTietTheLoaiTruyenID = new SelectList(db.ChiTietTheLoaiTruyen, "ChiTietTheLoaiTruyenID", "TenChiTietTheLoaiTruyen", post.ChiTietTheLoaiTruyenID);
            return View(post);
        }

        //
        // GET: /Post/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Post post = db.Post.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Post.Find(id);
            db.Post.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BaoCaoCuoiKy/www/WebFinalProject/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebFinalProject.Controllers
{
    public class TrangChuController : Controller
    {
        //
        // GET: /TrangChu/

        public ActionResult TrangChu()
        {
            return View();
        }

    }
}

BaoCaoCuoiKy/www/WebFinalProject/Views/TrangChu/TrangChu.cshtml
@{
    ViewBag.Title = "TrangChu";
    Layout = "~/Views/Shared/_WebProject.cshtml";
}
<body>
    <div class="panel" style="width:1080px; height:300px;background:#ffffff;border:solid 1px #f5f0f0; margin:10px 10px">
        <div class="panel" style="width:100px; height:30px; background:#ee9922; font-size:1.0em; text-align:center; font-weight:bold; margin-left:-4px; margin-bottom:8px">
            <article> Truyện ngắn</article>
        </div>
        <div class="panel" style="background:#ffffff; width:660px;float:left; margin:10px 10px; border:solid 2px #f5f0f0">
                <img src="~/Images/anh-duong-cua-toi.jpg" style="float:left" />
                <div style="width:300px; height:200px; float:right; text-align:center; margin-right:30px; margin-top:10px; font-weight:bold">
                    @Html.ActionLink("Ánh Dương là của tôi","AnhDuongLaCuaToi","Post")
                    <br />
                    <content>
                        Tôi là một gã trai tồi, như người ta hay gọi là playboy.
                        Tôi thay người yêu như thay áo, với tôi, đàn bà chỉ là thứ tạm bợ xoa dịu cho trái tim hoang hoải và tâm hồn cô đơn của mình.

                        Chưa bao giờ tôi nghĩ, sẽ có một cô gái trói buộc được trái tim rong ruổi như cơn gió hoang của mình...
                    </content>
                </div>
            </div>
        <div class="panel" style="background:#ffffff; width:300px; float:right; border:thin; margin:0 0; padding-top:10px; margin-top:10px; margin-right:40px; font-weight:bold">
            @Html.ActionLink("☼ Được yêu anh là may mắn của em", "TrangChu", "TrangChu")
            <br />
            <br />
            @Html.ActionLink("☼ Hoa muống biển", "TrangChu", "TrangChu")
            <br />
            <br />
            @Html.ActionLink("☼ Định mệnh", "TrangChu", "TrangChu")
            <br />
            <br />
            @Html.ActionLink("☼ Bản họa không kết", "TrangChu", "TrangChu")
            <br />
            <br />
            <div style="width:100px; height:50px; float:right; text-align:center">
                @Html.ActionLink("Xem tất cả", "TrangChu", "TrangChu")

            </div>
        </div>
    </div>
</body>

BaoCaoCuoiKy/www/WebFinalProject/Views/TrangChu/TrangChuSauDangNhap.cshtml
@{
    ViewBag.Title = "TrangChuSauDangNhap";
    Layout = "~/Views/Shared/_WebProject.cshtml";
}

<h2>TrangChuSauDangNhap</h2>